# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solo',
            name='artist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solo',
            name='instrument',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='solo',
            name='track',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
