# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solos', '0003_auto_20170318_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='solo',
            name='slug',
            field=models.SlugField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solo',
            name='album',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='solo',
            name='artist',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='solo',
            name='instrument',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solo',
            name='track',
            field=models.CharField(max_length=100),
        ),
    ]
